Add sitemap and PWA support in landing page
elixir-cloud-aai/landing-page pull request #129
Opened 2024-09-29 10:28 UTC by dhararaghu777

2024-10-01 18:58 UTC, anuragxxd requested changes
Some changes otherwise lgtm

2024-10-01 18:58 UTC, anuragxxd commented on public/sitemap-0.xml
This shouldn't be commited! Right?

2024-10-01 18:58 UTC, anuragxxd commented on public/sitemap.xml
This too!

2024-10-01 18:58 UTC, anuragxxd commented on public/sw.js
Same!

2024-10-05 16:07 UTC, dhararaghu777 commented on public/sitemap-0.xml
Yeah these will be generated during the build, I will remove them and push again

2024-10-05 16:11 UTC, dhararaghu777 commented on public/sitemap-0.xml
Resolved

2024-10-05 16:11 UTC, dhararaghu777 commented on public/sw.js
Resolved

2024-10-07 15:08 UTC, anuragxxd approved these changes

2024-10-07 15:08 UTC, merged