feat: removed guides, added doc links
elixir-cloud-aai/landing-page pull request #84
Opened 2023-01-14 00:34 UTC by samyak-max

![image](https://user-images.githubusercontent.com/76250685/212441420-71027863-683c-4bce-8259-53ab3054614a.png)

Removed guides link from nav and logic for the page (deleted Guides component, guide page, and /guide/[id]), added docs links.

2023-01-15 17:52 UTC, git-anurag-hub requested changes
Just one thing, give a little bit more padding at the bottom of the footer. Other than that LGTM!

2023-01-15 17:52 UTC, git-anurag-hub commented on components/Footer.jsx
> +          link: ' https://elixir-cloud-aai.github.io/guides/guide-admin/',
Remove trailing spaces!

2023-01-16 08:48 UTC, git-anurag-hub approved these changes

2023-01-16 08:49 UTC, git-anurag-hub submitted a review, later dismissed

2023-01-16 08:49 UTC, git-anurag-hub commented
Hey @uniqueg LGTM! 
You can have a look if you want!

2023-01-16 09:22 UTC, uniqueg requested changes
Looks great - just one minor detail: Perhaps rather than having a separate "Home" item in the "Docs" section in the footer, you could link the "Docs" section title itself. I know it's not consistent with the behavior of the other section titles, but I think it still makes sense and saves us some space.

2023-01-16 09:28 UTC, uniqueg commented
Also, another minor detail: I changed the PR title. Please always use present tense for semantic commit messages.

2023-01-16 19:31 UTC, uniqueg approved these changes

2023-01-16 19:32 UTC, merged