feat: Google Analytics support
elixir-cloud-aai/landing-page pull request #97
Opened 2023-02-13 15:22 UTC by tanya17-05

resolves #52 
to see logs use [google analytics debugger chrome extension](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna/related?hl=en)

2023-02-13 19:03 UTC, uniqueg submitted a review, later dismissed
Awesome! LGTM. Anything from your side, @git-anurag-hub? If not, I think you can go ahead and merge

2023-02-18 09:09 UTC, git-anurag-hub requested changes

2023-02-21 07:45 UTC, tanya17-05 commented on components/CookieConsent.js
> +import ReactGA from 'react-ga4';
That's true @git-anurag-hub, but I guess, we may run not able to track cookies as per user instructions. Script will be inserted in the webpage, regardless of user consent.

2023-02-21 11:03 UTC, uniqueg commented on components/CookieConsent.js
> +import ReactGA from 'react-ga4';
And that's of course important. What do you say, @git-anurag-hub, do you know a better method that still regards the user's consent? If not, I guess you can resolve the issue and merge.

Thanks @tanya17-05

2023-06-14 20:33 UTC, uniqueg commented on components/CookieConsent.js
> +import ReactGA from 'react-ga4';
@git-anurag-hub: Any update on this? Would be nice to get this in...

2023-08-15 21:40 UTC, git-anurag-hub requested changes

2023-08-15 21:41 UTC, git-anurag-hub commented on components/CookieConsent.js
> +import ReactGA from 'react-ga4';
Ahh, I actually did review this but forgot to hit submit so the review what pending from March 2nd. Will take this on priority!

2023-09-18 06:59 UTC, closed without merging